import type { Language } from '../components/language-context'

export type PortfolioWork = {
  id: string
  title: string
  type: string
  category: string
  year: string
  status: string
  role: string
  methods: string
  next: string
  description: string
  question: string
  process: [string, string][]
  outcomes: string[]
  research?: {
    sample: string
    metrics: [string, string, string][]
    decisions: [string, string][]
    limitation: string
  }
  delivery?: [string, string][]
  image?: string
  detailImage?: string
  href: string
}

const image = (name: string) => `/works/portfolio/${name}.PNG`

export const portfolioWorks: Record<Language, PortfolioWork[]> = {
  en: [
    {
      id: 'co-creative-ai-training',
      title: 'Co-creative AI Training Interface',
      type: 'AI interaction / Co-creation',
      category: 'AI interaction / Co-creation',
      year: '2025-2026',
      status: 'Concept system in progress',
      role: 'Interaction concept, UI framing, training-data flow',
      methods: 'Human agency mapping, UI prototyping, AI workflow design',
      next: 'Turn the concept into a clearer screen flow and define what user actions become training signals.',
      description: 'A UI concept that makes user intention, correction, and authorship visible before those actions become AI training data.',
      question: 'How can an AI system become specialized through co-creation without hiding the user behind automated training logic?',
      process: [
        ['Agency trigger', 'Use explicit UI moments to make users aware of when they are directing the AI, correcting it, or adding intent.'],
        ['Visible contribution', 'Convert buttons, choices, corrections, and comments into visible data traces instead of invisible backend events.'],
        ['Training loop', 'Let the system learn from structured human input while preserving the feeling that the user remains the author.'],
      ],
      outcomes: [
        'Frames AI training as a co-creative process rather than passive data extraction.',
        'Makes user control and contribution visible in the interface.',
        'Creates a base for future specialized AI workflows.',
      ],
      image: image('1op'),
      href: '/works#co-creative-ai-training',
    },
    {
      id: 'transparent-driving-hud',
      title: 'Transparent Driving AR-HUD',
      type: 'Mobility HMI / AR-HUD',
      category: 'Mobility HMI / AR-HUD',
      year: '2025-2026',
      status: 'Research concept',
      role: 'HMI research, safety framing, Kansei evaluation plan',
      methods: 'Scenario design, AR-HUD concept, human-factors review',
      next: 'Build video stimuli for baseline, rational-transparent, and emotional-attention HUD variants.',
      description: 'An AR-HUD concept that visualizes vehicle relationships, uncertainty, and AI driving intention to reduce black-box anxiety.',
      question: 'How can automated driving show what it understands without overloading the driver or weakening takeover safety?',
      process: [
        ['Transparency layer', 'Show the key vehicles, blind-zone awareness, and uncertainty gradients that explain the AI decision.'],
        ['Coach layer', 'Use ghost paths and tactical hints to build confidence and willingness to drive manually.'],
        ['Safety exit', 'Remove playful or nonessential overlays within 500 ms during takeover requests, leaving only critical warnings.'],
      ],
      outcomes: [
        'Connects trust, attention, and legal constraints in one HMI story.',
        'Defines a research path using video-based Kansei evaluation.',
        'Positions AR-HUD as a glass-box interface for human-machine driving.',
      ],
      image: image('2op'),
      href: '/works#transparent-driving-hud',
    },
    {
      id: 'japanese-practice-echoes',
      title: 'Japanese Practice with Echoes',
      type: 'Learning UX / AI companion',
      category: 'Learning UX / AI companion',
      year: '2025-2026',
      status: 'App concept and demo board',
      role: 'Learning experience, feedback model, UI storytelling',
      methods: 'Practice-flow design, growth trace mapping, feedback UI',
      next: 'Prototype the speaking session and effort trace map as an interactive mobile flow.',
      description: 'A Japanese learning app that records hesitation, rereading, pauses, and progress as evidence of growth.',
      question: 'What if AI did not replace language learning, but helped learners see the effort that usually disappears?',
      process: [
        ['Practice capture', 'Record speaking time, pauses, retries, and phrases that became smoother.'],
        ['Gentle feedback', 'Give feedback after practice instead of interrupting the learner while speaking.'],
        ['Growth evidence', 'Turn repeated effort into a personal map that says: I am getting stronger.'],
      ],
      outcomes: [
        'Reduces shame by treating pauses as part of growth.',
        'Makes language practice feel accompanied rather than corrected.',
        'Preserves personal learning history as visible evidence.',
      ],
      image: image('3op'),
      detailImage: image('3en'),
      href: '/works#japanese-practice-echoes',
    },
    {
      id: 'frametrace',
      title: 'FrameTrace',
      type: 'AR glasses / Travel photography',
      category: 'AR glasses / Travel photography',
      year: '2025-2026',
      status: 'Concept research · Prototype in progress',
      role: 'Independent research, spatial UX, AR interaction, and Quest 3 prototyping',
      methods: '106-response survey, sensitivity analysis, scenario design, and spatial prototyping',
      next: 'Turn survey priorities into the next prototype, then test it with 6–10 Quest 3 participants.',
      description: 'An AR travel-photography system that turns public viewpoints and private photo memories into reusable spatial traces.',
      question: 'How can photographic experience remain at a real place so another person—or a future self—can safely revisit it?',
      process: [
        ['Test the concept', 'Used a 106-response formative survey to compare core concepts, side features, concerns, and overall impression.'],
        ['Identify a direction', 'The results suggest testing public viewpoint recreation as the main task and private-photo revisiting as a separate emotional branch.'],
        ['Build the next prototype', 'The proposed flow, walking states, consent, and private-photo revisit still need implementation and behavioral validation.'],
      ],
      outcomes: [
        'Overall concept reached 5.65/7 in the primary analysis (N=82).',
        'Public viewpoint recreation was the most chosen single priority; private-photo revisiting scored highest at 5.81/7.',
        'Privacy, explainable recommendations, and walking safety are priorities for the next prototype.',
      ],
      image: '/works/frametrace/hero.jpg',
      href: '/works/frametrace',
    },
    {
      id: 'taste-again',
      title: 'Long Time No Taste',
      type: 'WeChat mini program / Food memory',
      category: 'WeChat mini program / Food memory',
      year: '2025-2026',
      status: 'Working MVP · User testing next',
      role: 'Independent product definition, research, UX/UI, and mini-program implementation',
      methods: 'Formative survey, behavior-loop design, information architecture, and mobile prototyping',
      next: 'Run task-based usability sessions and a seven-day field test.',
      description: 'A private food-memory WeChat mini program that records a meal and its feeling, then brings a forgotten favorite back when time and context fit.',
      question: 'Instead of adding more choices, can a personal food-memory tool reduce decision fatigue by bringing back something the user already loved?',
      process: [
        ['Reframe the problem', 'Shifted from adding food choices to reducing choice overload and closing the gap between remembering a flavor and acting on it.'],
        ['Design the memory loop', 'Connected current feeling, a lightweight record, visible accumulation, and a contextual reunion.'],
        ['Build the experience', 'Created a working mini program from onboarding and recording through memory retrieval and repeat tasting.'],
      ],
      outcomes: [
        'Reduced meal choice to a few personally meaningful candidates.',
        'Turned lightweight records into visible reasons to return.',
        'Delivered a working, private-by-default MVP ready for user testing.',
      ],
      image: '/works/portfolio/haojiu-meichi-cover.png',
      href: '/works/taste-again',
    },
    {
      id: 'fridge-timeline',
      title: 'Fridge Timeline System',
      type: 'Product system / Food management',
      category: 'Product system / Food management',
      year: '2023',
      status: 'University graduation project',
      role: 'Product-service system, hardware interaction, behavior design',
      methods: 'User journey, hardware scenario, light-guidance interaction',
      next: 'Detail the scanner-device behavior and connect it to a clearer cooking-planning flow.',
      description: 'A fridge behavior system that makes food location and expiration visible through scanning, placement guidance, and light cues.',
      question: 'How can a fridge help users remember both where food is and when it should be used?',
      process: [
        ['Before storing', 'Scan groceries with a magnetic camera module and register type, purchase date, and expected shelf life.'],
        ['While storing', 'Recommend a fridge area and use lights to guide where the item should be placed.'],
        ['When cooking', 'Use phone, fridge screen, and internal lights to find ingredients and plan meals before they expire.'],
      ],
      outcomes: [
        'Transforms the fridge from storage space into a time-management interface.',
        'Connects hardware, mobile UI, and internal lighting into one behavior loop.',
        'Supports less food waste and more organized cooking habits.',
      ],
      image: image('6op'),
      detailImage: image('6en'),
      href: '/works#fridge-timeline',
    },
  ],
  ja: [
    {
      id: 'co-creative-ai-training',
      title: '共創特化AIトレーニングUI',
      type: 'AIインタラクション / 共創',
      category: 'AIインタラクション / 共創',
      year: '2025-2026',
      status: 'コンセプト制作中',
      role: 'インタラクション構想、UI設計、学習データフロー',
      methods: '主体性マッピング、UIプロトタイプ、AIワークフロー設計',
      next: 'ユーザー操作がどのように学習信号になるかを、画面遷移として具体化する。',
      description: 'ユーザーの意図、修正、判断を可視化し、それをAI学習に接続するためのUIコンセプト。',
      question: 'AIを特化させる過程で、ユーザーの主導権や共創感をどのように残せるか。',
      process: [
        ['主体性の誘発', 'ユーザーがAIを導く、修正する、意図を加える瞬間をUI上で明確にする。'],
        ['貢献の可視化', 'ボタン、選択、修正、コメントを見えないログではなく、見えるデータの痕跡にする。'],
        ['学習ループ', '構造化された人間の入力からAIが学びつつ、ユーザーが作者である感覚を保つ。'],
      ],
      outcomes: ['AI学習を受動的なデータ収集ではなく共創として扱う。', 'ユーザーの制御と貢献をインターフェース上に残す。', '特化型AIのための基礎的なワークフローを提示する。'],
      image: image('1op'),
      href: '/works#co-creative-ai-training',
    },
    {
      id: 'transparent-driving-hud',
      title: '自動運転の透明化AR-HUD',
      type: 'モビリティHMI / AR-HUD',
      category: 'モビリティHMI / AR-HUD',
      year: '2025-2026',
      status: '研究コンセプト',
      role: 'HMIリサーチ、安全性整理、感性評価計画',
      methods: 'シナリオ設計、AR-HUD構想、人因工学レビュー',
      next: 'ベースライン、透明化版、感性注意力版の比較動画刺激を制作する。',
      description: '車間関係、不確実性、AIの運転意図をAR-HUDで示し、ブラックボックス感を減らすコンセプト。',
      question: '自動運転は、ドライバーに過負荷を与えずに、自分が何を理解しているかをどう示せるか。',
      process: [
        ['透明化レイヤー', 'AI判断を説明する重要車両、死角認識、不確実性の変化を表示する。'],
        ['コーチレイヤー', 'ゴースト経路や運転のヒントで、手動運転への自信と意欲を支える。'],
        ['安全な退場', '接管要求時には500ms以内に遊び要素を消し、重要警告だけを残す。'],
      ],
      outcomes: ['信頼、注意、法規制をひとつのHMIストーリーとして接続する。', '動画ベースの感性評価という研究方法を定義する。', 'AR-HUDを人と車のための透明なインターフェースとして位置づける。'],
      image: image('2op'),
      href: '/works#transparent-driving-hud',
    },
    {
      id: 'japanese-practice-echoes',
      title: 'こだまする日本語練習',
      type: '学習UX / AI伴走',
      category: '学習UX / AI伴走',
      year: '2025-2026',
      status: 'アプリコンセプトとデモボード',
      role: '学習体験、フィードバックモデル、UIストーリー',
      methods: '練習フロー設計、成長痕跡マップ、フィードバックUI',
      next: '音読セッションと努力の痕跡マップを操作できるモバイルフローへ展開する。',
      description: 'つまずき、読み直し、停滞、進歩を成長の証拠として残す日本語練習アプリ。',
      question: 'AIが学習を代替するのではなく、消えがちな努力を見えるようにすると何が変わるか。',
      process: [['練習の記録', '発話時間、停滞、読み直し、自然に読めた表現を記録する。'], ['やさしい反馈', '発話中に遮らず、練習後に伴走者のように整理して返す。'], ['成長の証拠', '反復した努力を個人の成長マップとして保存する。']],
      outcomes: ['停滞や読み直しを失敗ではなく成長の一部として扱う。', '学習者が責められるより、伴走されている感覚を持てる。', '個人的な学習履歴を見える証拠として残す。'],
      image: image('3op'),
      detailImage: image('3jp'),
      href: '/works#japanese-practice-echoes',
    },
    {
      id: 'frametrace',
      title: 'FrameTrace',
      type: 'ARグラス / 旅行写真',
      category: 'ARグラス / 旅行写真',
      year: '2025-2026',
      status: 'コンセプト調査・プロトタイプ制作中',
      role: '調査、空間UX、ARインタラクション、Quest 3プロトタイプを独立制作',
      methods: '106件の質問紙、感度分析、シナリオ設計、空間プロトタイピング',
      next: '調査結果を次のプロトタイプへ反映し、6〜10名のQuest 3テストを行う。',
      description: '公共の撮影位置と個人の写真記憶を、現地で再利用できる空間トレースへ変えるAR旅行写真システム。',
      question: '撮影経験を現実の場所に残し、他者や未来の自分が安全に再訪できるか。',
      process: [['概念を調査', '106件の形成的質問紙で、主要概念、支援機能、懸念、全体印象を比較した。'], ['方向を特定', '公共撮影位置の再現を主タスク、個人写真の再訪を別の感情的支線として試す示唆を得た。'], ['次の試作へ', '提案フロー、歩行状態、同意、個人写真再訪は、これから実装と行動検証を行う。']],
      outcomes: ['主分析N=82で全体概念は5.65/7。', '公共撮影位置の再現は単一優先で最多、個人写真の再訪は5.81/7で最高評価。', 'プライバシー、推薦理由、歩行安全は次のプロトタイプの優先課題。'],
      image: '/works/frametrace/hero.jpg',
      href: '/works/frametrace',
    },
    {
      id: 'taste-again',
      title: '好久没吃',
      type: 'WeChatミニプログラム / 食の記憶',
      category: 'WeChatミニプログラム / 食の記憶',
      year: '2025-2026',
      status: '実動MVP・次はユーザーテスト',
      role: 'プロダクト定義、調査、UX/UI、ミニプログラム実装',
      methods: '形成的調査、行動ループ設計、情報設計、モバイルプロトタイピング',
      next: 'タスク型可用性テストと7日間の実使用検証を行う。',
      description: '食べたものとその時の気持ちを個人の記憶として残し、時間と状況が合う時に忘れていた好みを思い出させるWeChatミニプログラム。',
      question: '選択肢を増やすのではなく、過去に好きだった味を戻すことで、日々の食事選択の負担を減らせるか。',
      process: [
        ['問題を捉え直す', '選択肢の追加ではなく、選択過多と、味を思い出しても行動しない断点に注目した。'],
        ['記憶ループを設計', '今の気分、軽い記録、蓄積の可視化、状況に合う再会をつないだ。'],
        ['体験を実装', '導入と記録から記憶検索、再食まで動くミニプログラムを制作した。'],
      ],
      outcomes: ['選択を個人的に意味のある少数候補へ減らした。', '軽い記録を、次に戻る理由として可視化した。', 'ユーザーテスト可能な非公開既定のMVPを完成した。'],
      image: '/works/portfolio/haojiu-meichi-cover.png',
      href: '/works/taste-again',
    },
    {
      id: 'fridge-timeline',
      title: 'Fridge Timeline System',
      type: 'プロダクトシステム / 食材管理',
      category: 'プロダクトシステム / 食材管理',
      year: '2023',
      status: '大学卒業制作',
      role: 'プロダクトサービスシステム、ハードウェア連携、行動設計',
      methods: 'ユーザージャーニー、ハードウェアシナリオ、ライトガイド',
      next: 'スキャナーの行動と料理計画フローをさらに明確化する。',
      description: '食材の位置と期限を、スキャン、置き場所の案内、ライト表示で見えるようにする冷蔵庫システム。',
      question: '冷蔵庫は、食材がどこにあるかだけでなく、いつ使うべきかも知らせられるか。',
      process: [['入れる前', '磁吸式カメラモジュールで食材をスキャンし、種類、購入日、保存期限を登録する。'], ['入れる時', '保存場所を推薦し、ライトで置く位置を案内する。'], ['料理する時', 'スマホ、冷蔵庫画面、内部ライトで食材を見つけ、期限前の料理計画につなげる。']],
      outcomes: ['冷蔵庫を保存空間から時間管理インターフェースへ変える。', 'ハードウェア、モバイルUI、内部ライトをひとつの行動ループにする。', '食品ロス削減と整理された料理習慣を支える。'],
      image: image('6op'),
      detailImage: image('6jp'),
      href: '/works#fridge-timeline',
    },
  ],
  zh: [
    {
      id: 'co-creative-ai-training',
      title: '个人判断价值提升界面',
      type: 'AI 产品体验 / 毕业设计',
      category: 'AI 产品体验 / 毕业设计',
      year: '2025-2026',
      status: '毕业设计进行中',
      role: '交互概念、UI 架构、判断分担机制与眼动验证流程',
      methods: '聊天调查、故事流程模拟、比较 UI、眼动追踪',
      next: '继续比较不同分担提示是否改变视线分配、判断信心和最终选择。',
      description: 'AI 共创的问题不只是回答质量，而是用户的判断很容易被输出结果盖过去；界面先让用户判断这一步谁负责，再让 AI 根据分担关系调整回答。',
      question: 'AI 共创不是让用户等一个答案，而是要让用户知道自己的判断在哪一步仍然有价值。',
      process: [['意图表达', '用户先表达目标、价值倾向和限制条件，明确自己真正重视的点。'], ['判断分担', '在 AI 代行、AI 商谈、用户决定之间选择责任关系，让分担成为显性行为。'], ['反馈学习', '用户确认和再调整会沉淀分担数据，让系统逐渐学习个人判断偏好。']],
      outcomes: ['把共创从“等 AI 输出”变成“判断分担 - 响应调整 - 反馈学习”的循环。', 'AI 根据分担关系调整提案粒度、解释强度、追问策略和结论强度。', '眼动追踪和比较 UI 用来观察提示是否真的改变注意路径与判断过程。'],
      image: image('1op'),
      href: '/works#co-creative-ai-training',
    },
    {
      id: 'transparent-driving-hud',
      title: '驾驶关注价值界面',
      type: '智能驾驶 / 关注价值 HMI',
      category: '智能驾驶 / 关注价值 HMI',
      year: '2025-2026',
      status: '关注价值 HMI 概念',
      role: 'HMI 研究、驾驶关注设计、安全边界与用户主观体验测试计划',
      methods: '驾驶场景拆解、提示强度比较、信息负担梳理',
      next: '比较情绪化短句、重点对象明示和指导化提示对注意力与分心的影响。',
      description: '智驾越稳定，人越容易把驾驶交出去；这个界面不堆行车参数，而是说清 AI 正在担心哪里。',
      question: '高价值驾驶不该只剩交通工具。HMI 要怎样让人继续参与路面判断，而不是安静退成乘客？',
      process: [['驾驶意愿', '智驾会逐渐影响真实驾驶意愿；如果人只负责坐着，高价值车的体验会被压成工具属性。'], ['AI 关注明示', '增加信任只是基础。更重要的是让 AI 明示自己正在关注哪些可能造成问题的重点位置。'], ['情绪化警示', '小朋友可能闯出、旁车可能靠近，用表情和短句让危险被立刻理解。']],
      outcomes: ['按危险程度控制提示强度，画面保持克制，在安全边界内保留人的驾驶关注价值。', '这个方向讨论的不是普通参数提示，而是 AI 如何把“它正在担心什么”讲给驾驶者。', '评价重点会放在理解负担、分心风险、注意保持和接管前信息清晰度。'],
      image: image('2op'),
      href: '/works#transparent-driving-hud',
    },
    {
      id: 'frametrace',
      title: 'FrameTrace',
      type: 'MR 眼镜 / 跨时间摄影',
      category: 'MR 眼镜 / 跨时间摄影',
      year: '2025-2026',
      status: 'Quest 3 原型进行中',
      role: '独立完成调研、空间 UX、MR 交互与 Quest 3 原型',
      methods: '106 份问卷、敏感性分析、场景设计与空间原型',
      next: '用 Quest 3 观察寻找机位、行走对齐、手势取景和相机焦距提示是否能被自然理解。',
      description: '看到一张经典照片时，人会想知道它当时是站在哪里、用什么角度拍出来的。FrameTrace 把这个问题变成跨越时间和空间的摄影交友。',
      question: '用户能看到成片，却通常不知道拍摄者站在哪里、看向哪里、用什么焦距和姿态完成那张照片。',
      process: [['经典怎么拍', '把机位、焦距、构图和拍摄姿态从照片结果中拆出来，理解那张照片为什么成立。'], ['时间同场', 'MR 眼镜把不同年份、不同拍摄者的痕迹放回同一地点，让过去成为现场里的另一个人。'], ['共同完成', '用户沿着取景、对齐和焦距提示，像和过去的拍摄者一起完成一张照片。']],
      outcomes: ['把“这张经典怎么拍的”变成可行走、可对齐、可共同完成的跨时间摄影。', '主分析 N=82 中，整体概念第一印象为 5.65/7。', '隐私、推荐解释与行走安全是下一版原型的优先课题。'],
      image: '/works/frametrace/hero.jpg',
      href: '/works/frametrace',
    },
    {
      id: 'taste-again',
      title: '好久没吃',
      type: '微信小程序 / 饮食记忆',
      category: '微信小程序 / 饮食记忆',
      year: '2025-2026',
      status: 'MVP 可运行',
      role: '独立完成产品定义、调研、UX/UI 与微信小程序实现',
      methods: '形成性调研、行为闭环设计、信息架构与移动端原型',
      next: '用任务测试和 7 天使用观察，看它是否真的能在某个“好久没吃”的时刻带来一次再吃。',
      description: '吃什么不总是搜索问题。很多时候只是突然想起：那一碗，好久没吃了。',
      question: '吃可以是周期的，也可以是感觉的。总有那么一周一次，会想起那一家、那一碗。',
      process: [
        ['个人规律', '饮食有周期，嘴馋也有周期。一周总会想吃那一家、那一碗，这比泛推荐更接近真实选择。'],
        ['味道线索', '记录店、菜、时间和当时的感觉，让用户从自己的经历里找到今天想吃什么。'],
        ['回到旧味道', '提醒不是催促，也不是扩大选择，而是带理由地帮用户回到某个具体味道。'],
      ],
      outcomes: ['让个人饮食记忆成为选择入口，而不是把用户推向更大的推荐列表。', '“好久没吃”不是催促，而是带理由、可拒绝的回忆提示。', '当前 MVP 已完成核心流程，下一步看它是否真的带来一次再吃。'],
      image: '/works/portfolio/haojiu-meichi-cover.png',
      href: '/works/taste-again',
    },
    {
      id: 'fridge-timeline',
      title: 'FRIDGE TIMELINE SYSTEM',
      type: '大学毕业设计 / 食材日期管理',
      category: '大学毕业设计 / 食材日期管理',
      year: '2023',
      status: '大学毕业设计',
      role: '产品服务系统、硬件交互、行为设计',
      methods: '用户旅程、硬件场景、灯光引导交互',
      next: '继续把磁吸扫描、手机提醒、灯光定位和料理计划接得更自然。',
      description: '让临期食材被看见、被注意，而不是在冰箱深处慢慢被忘掉。',
      question: '这个系统的重点不是多一个提醒，而是通过可见的临期状态，培养用户管理食品日期的习惯。',
      process: [['临期可见', '把临期状态从手机提醒变成冰箱里的可见信息，让用户开门时就知道哪些食材需要优先处理。'], ['注意触发', '灯光不是装饰，而是把视线引到具体位置，让“快过期了”变成此刻能被注意到的状态。'], ['习惯形成', '扫描、存放和手机联动不是单独功能，而是在反复使用中帮助用户建立日期管理习惯。']],
      outcomes: ['让临期被看见、被注意，并把日期管理习惯拆进日常开门和取用动作。', '手机 UI、冰箱屏幕和内部灯光分别承担远程提醒、查看和定位。', '毕业设计完成了产品服务系统概念，硬件实现仍需要进一步工程验证。'],
      image: image('6op'),
      detailImage: image('6cn'),
      href: '/works#fridge-timeline',
    },
  ],
}
