import type { Language } from '../components/language-context'

export type PortfolioWork = {
  id: string
  title: string
  type: string
  category: string
  year: string
  status: string
  role: string
  methods: string
  next: string
  description: string
  question: string
  process: [string, string][]
  outcomes: string[]
  image?: string
  detailImage?: string
  href: string
}

const image = (name: string) => `/works/portfolio/${name}.PNG`

export const portfolioWorks: Record<Language, PortfolioWork[]> = {
  en: [
    {
      id: 'co-creative-ai-training',
      title: 'Co-creative AI Training Interface',
      type: 'AI interaction / Co-creation',
      category: 'AI interaction / Co-creation',
      year: '2025-2026',
      status: 'Concept system in progress',
      role: 'Interaction concept, UI framing, training-data flow',
      methods: 'Human agency mapping, UI prototyping, AI workflow design',
      next: 'Turn the concept into a clearer screen flow and define what user actions become training signals.',
      description: 'A UI concept that makes user intention, correction, and authorship visible before those actions become AI training data.',
      question: 'How can an AI system become specialized through co-creation without hiding the user behind automated training logic?',
      process: [
        ['Agency trigger', 'Use explicit UI moments to make users aware of when they are directing the AI, correcting it, or adding intent.'],
        ['Visible contribution', 'Convert buttons, choices, corrections, and comments into visible data traces instead of invisible backend events.'],
        ['Training loop', 'Let the system learn from structured human input while preserving the feeling that the user remains the author.'],
      ],
      outcomes: [
        'Frames AI training as a co-creative process rather than passive data extraction.',
        'Makes user control and contribution visible in the interface.',
        'Creates a base for future specialized AI workflows.',
      ],
      image: image('1op'),
      href: '/works#co-creative-ai-training',
    },
    {
      id: 'transparent-driving-hud',
      title: 'Transparent Driving AR-HUD',
      type: 'Mobility HMI / AR-HUD',
      category: 'Mobility HMI / AR-HUD',
      year: '2025-2026',
      status: 'Research concept',
      role: 'HMI research, safety framing, Kansei evaluation plan',
      methods: 'Scenario design, AR-HUD concept, human-factors review',
      next: 'Build video stimuli for baseline, rational-transparent, and emotional-attention HUD variants.',
      description: 'An AR-HUD concept that visualizes vehicle relationships, uncertainty, and AI driving intention to reduce black-box anxiety.',
      question: 'How can automated driving show what it understands without overloading the driver or weakening takeover safety?',
      process: [
        ['Transparency layer', 'Show the key vehicles, blind-zone awareness, and uncertainty gradients that explain the AI decision.'],
        ['Coach layer', 'Use ghost paths and tactical hints to build confidence and willingness to drive manually.'],
        ['Safety exit', 'Remove playful or nonessential overlays within 500 ms during takeover requests, leaving only critical warnings.'],
      ],
      outcomes: [
        'Connects trust, attention, and legal constraints in one HMI story.',
        'Defines a research path using video-based Kansei evaluation.',
        'Positions AR-HUD as a glass-box interface for human-machine driving.',
      ],
      image: image('2op'),
      href: '/works#transparent-driving-hud',
    },
    {
      id: 'japanese-practice-echoes',
      title: 'Japanese Practice with Echoes',
      type: 'Learning UX / AI companion',
      category: 'Learning UX / AI companion',
      year: '2025-2026',
      status: 'App concept and demo board',
      role: 'Learning experience, feedback model, UI storytelling',
      methods: 'Practice-flow design, growth trace mapping, feedback UI',
      next: 'Prototype the speaking session and effort trace map as an interactive mobile flow.',
      description: 'A Japanese learning app that records hesitation, rereading, pauses, and progress as evidence of growth.',
      question: 'What if AI did not replace language learning, but helped learners see the effort that usually disappears?',
      process: [
        ['Practice capture', 'Record speaking time, pauses, retries, and phrases that became smoother.'],
        ['Gentle feedback', 'Give feedback after practice instead of interrupting the learner while speaking.'],
        ['Growth evidence', 'Turn repeated effort into a personal map that says: I am getting stronger.'],
      ],
      outcomes: [
        'Reduces shame by treating pauses as part of growth.',
        'Makes language practice feel accompanied rather than corrected.',
        'Preserves personal learning history as visible evidence.',
      ],
      image: image('3op'),
      detailImage: image('3en'),
      href: '/works#japanese-practice-echoes',
    },
    {
      id: 'frametrace',
      title: 'FrameTrace',
      type: 'AR glasses / Travel photography',
      category: 'AR glasses / Travel photography',
      year: '2025-2026',
      status: 'System concept and service scenario',
      role: 'AR interaction, gesture framing, spatial memory system',
      methods: 'Gesture scenario, spatial UX, service blueprint',
      next: 'Define MVP features separately from future shared spatial-memory functions.',
      description: 'An AR glasses system that uses hand-frame gestures to guide travel photo composition, focal length, position, and pose.',
      question: 'Can good photo experience be transferred from online image references into the real place where the photo is taken?',
      process: [
        ['Gesture framing', 'Use a two-hand frame gesture as a quick, natural way to enter composition mode.'],
        ['AR guidance', 'Recommend focal length, movement distance, tilt, and frame size directly in the scene.'],
        ['Photo trace', 'Save location, direction, lens, pose, and composition records for others to reference later.'],
      ],
      outcomes: [
        'Turns travel photography from trial-and-error into spatial guidance.',
        'Connects personal photo memory with shared AR references.',
        'Keeps future metaverse-like ideas grounded in an MVP path.',
      ],
      image: image('4op'),
      detailImage: image('4en'),
      href: '/works#frametrace',
    },
    {
      id: 'taste-again',
      title: 'Taste Again',
      type: 'Food memory / Planning app',
      category: 'Food memory / Planning app',
      year: '2025-2026',
      status: 'UX concept and app board',
      role: 'Product concept, meal memory model, mobile UX',
      methods: 'Decision journey, timeline model, reminder design',
      next: 'Prototype meal cards, revisit cycles, and weekly planning interactions.',
      description: 'A meal memory app that helps people rediscover dishes they once loved at the right time.',
      question: 'How can everyday meal decisions begin from remembered favorites instead of starting from nothing every day?',
      process: [
        ['Record', 'Save meals as cards with taste profile, context, favorite level, and source.'],
        ['Set rhythm', 'Give every dish a revisit cycle based on frequency, season, and personal feedback.'],
        ['Revisit', 'Surface forgotten meals when the timing and mood become suitable again.'],
      ],
      outcomes: [
        'Reduces daily decision fatigue around food.',
        'Builds a personal database of taste memories.',
        'Turns recommendations into a gentle reunion with past favorites.',
      ],
      image: image('5op'),
      detailImage: image('5en'),
      href: '/works#taste-again',
    },
    {
      id: 'fridge-timeline',
      title: 'Fridge Timeline System',
      type: 'Product system / Food management',
      category: 'Product system / Food management',
      year: '2023',
      status: 'University graduation project',
      role: 'Product-service system, hardware interaction, behavior design',
      methods: 'User journey, hardware scenario, light-guidance interaction',
      next: 'Detail the scanner-device behavior and connect it to a clearer cooking-planning flow.',
      description: 'A fridge behavior system that makes food location and expiration visible through scanning, placement guidance, and light cues.',
      question: 'How can a fridge help users remember both where food is and when it should be used?',
      process: [
        ['Before storing', 'Scan groceries with a magnetic camera module and register type, purchase date, and expected shelf life.'],
        ['While storing', 'Recommend a fridge area and use lights to guide where the item should be placed.'],
        ['When cooking', 'Use phone, fridge screen, and internal lights to find ingredients and plan meals before they expire.'],
      ],
      outcomes: [
        'Transforms the fridge from storage space into a time-management interface.',
        'Connects hardware, mobile UI, and internal lighting into one behavior loop.',
        'Supports less food waste and more organized cooking habits.',
      ],
      image: image('6op'),
      detailImage: image('6en'),
      href: '/works#fridge-timeline',
    },
  ],
  ja: [
    {
      id: 'co-creative-ai-training',
      title: '共創特化AIトレーニングUI',
      type: 'AIインタラクション / 共創',
      category: 'AIインタラクション / 共創',
      year: '2025-2026',
      status: 'コンセプト制作中',
      role: 'インタラクション構想、UI設計、学習データフロー',
      methods: '主体性マッピング、UIプロトタイプ、AIワークフロー設計',
      next: 'ユーザー操作がどのように学習信号になるかを、画面遷移として具体化する。',
      description: 'ユーザーの意図、修正、判断を可視化し、それをAI学習に接続するためのUIコンセプト。',
      question: 'AIを特化させる過程で、ユーザーの主導権や共創感をどのように残せるか。',
      process: [
        ['主体性の誘発', 'ユーザーがAIを導く、修正する、意図を加える瞬間をUI上で明確にする。'],
        ['貢献の可視化', 'ボタン、選択、修正、コメントを見えないログではなく、見えるデータの痕跡にする。'],
        ['学習ループ', '構造化された人間の入力からAIが学びつつ、ユーザーが作者である感覚を保つ。'],
      ],
      outcomes: ['AI学習を受動的なデータ収集ではなく共創として扱う。', 'ユーザーの制御と貢献をインターフェース上に残す。', '特化型AIのための基礎的なワークフローを提示する。'],
      image: image('1op'),
      href: '/works#co-creative-ai-training',
    },
    {
      id: 'transparent-driving-hud',
      title: '自動運転の透明化AR-HUD',
      type: 'モビリティHMI / AR-HUD',
      category: 'モビリティHMI / AR-HUD',
      year: '2025-2026',
      status: '研究コンセプト',
      role: 'HMIリサーチ、安全性整理、感性評価計画',
      methods: 'シナリオ設計、AR-HUD構想、人因工学レビュー',
      next: 'ベースライン、透明化版、感性注意力版の比較動画刺激を制作する。',
      description: '車間関係、不確実性、AIの運転意図をAR-HUDで示し、ブラックボックス感を減らすコンセプト。',
      question: '自動運転は、ドライバーに過負荷を与えずに、自分が何を理解しているかをどう示せるか。',
      process: [
        ['透明化レイヤー', 'AI判断を説明する重要車両、死角認識、不確実性の変化を表示する。'],
        ['コーチレイヤー', 'ゴースト経路や運転のヒントで、手動運転への自信と意欲を支える。'],
        ['安全な退場', '接管要求時には500ms以内に遊び要素を消し、重要警告だけを残す。'],
      ],
      outcomes: ['信頼、注意、法規制をひとつのHMIストーリーとして接続する。', '動画ベースの感性評価という研究方法を定義する。', 'AR-HUDを人と車のための透明なインターフェースとして位置づける。'],
      image: image('2op'),
      href: '/works#transparent-driving-hud',
    },
    {
      id: 'japanese-practice-echoes',
      title: 'こだまする日本語練習',
      type: '学習UX / AI伴走',
      category: '学習UX / AI伴走',
      year: '2025-2026',
      status: 'アプリコンセプトとデモボード',
      role: '学習体験、フィードバックモデル、UIストーリー',
      methods: '練習フロー設計、成長痕跡マップ、フィードバックUI',
      next: '音読セッションと努力の痕跡マップを操作できるモバイルフローへ展開する。',
      description: 'つまずき、読み直し、停滞、進歩を成長の証拠として残す日本語練習アプリ。',
      question: 'AIが学習を代替するのではなく、消えがちな努力を見えるようにすると何が変わるか。',
      process: [['練習の記録', '発話時間、停滞、読み直し、自然に読めた表現を記録する。'], ['やさしい反馈', '発話中に遮らず、練習後に伴走者のように整理して返す。'], ['成長の証拠', '反復した努力を個人の成長マップとして保存する。']],
      outcomes: ['停滞や読み直しを失敗ではなく成長の一部として扱う。', '学習者が責められるより、伴走されている感覚を持てる。', '個人的な学習履歴を見える証拠として残す。'],
      image: image('3op'),
      detailImage: image('3jp'),
      href: '/works#japanese-practice-echoes',
    },
    {
      id: 'frametrace',
      title: 'FrameTrace',
      type: 'ARグラス / 旅行写真',
      category: 'ARグラス / 旅行写真',
      year: '2025-2026',
      status: 'システムコンセプト',
      role: 'ARインタラクション、手勢構図、空間記憶システム',
      methods: 'ジェスチャーシナリオ、空間UX、サービス設計',
      next: 'MVP機能と将来の空間共有機能を分けて整理する。',
      description: '手のフレームで構図を作り、焦点距離、撮影位置、姿勢をARでガイドする旅行写真支援システム。',
      question: 'オンライン上の写真ノウハウを、実際に写真を撮る場所の中へ移せるか。',
      process: [['手勢構図', '両手で作るフレームを、素早く自然な構図モードの入口にする。'], ['ARガイド', '焦点距離、移動距離、傾き、フレームサイズを現地の視野上に提示する。'], ['フォトトレース', '位置、方向、レンズ、姿勢、構図を保存し、後から来た人が参照できるようにする。']],
      outcomes: ['旅行写真を試行錯誤から空間ガイド付きの体験へ変える。', '個人の撮影記憶と共有AR参照をつなげる。', '未来的な構想をMVPに落とし込んで示す。'],
      image: image('4op'),
      detailImage: image('4jp'),
      href: '/works#frametrace',
    },
    {
      id: 'taste-again',
      title: '料理再会',
      type: '食の記憶 / 計画アプリ',
      category: '食の記憶 / 計画アプリ',
      year: '2025-2026',
      status: 'UXコンセプトとアプリボード',
      role: 'プロダクト構想、料理記憶モデル、モバイルUX',
      methods: '意思決定ジャーニー、タイムラインモデル、リマインド設計',
      next: '料理カード、再食周期、週間計画の操作をプロトタイプ化する。',
      description: '過去に好きだった料理を、ちょうどよいタイミングで思い出させる料理記憶アプリ。',
      question: '毎日の食事選びを、ゼロから考えるのではなく、過去のおいしい記憶から始められるか。',
      process: [['記録する', '料理を味の特徴、場面、好み、入手方法と一緒にカード化する。'], ['リズムを設定', '料理ごとに頻度、季節、満足度から再食周期を持たせる。'], ['再会する', '時間と気分が合うときに、忘れていた料理をやさしく浮上させる。']],
      outcomes: ['毎日の食事選択の負担を減らす。', '個人の料理記憶データベースを作る。', '推薦を「過去のおいしさとの再会」に変える。'],
      image: image('5op'),
      detailImage: image('5jp'),
      href: '/works#taste-again',
    },
    {
      id: 'fridge-timeline',
      title: 'Fridge Timeline System',
      type: 'プロダクトシステム / 食材管理',
      category: 'プロダクトシステム / 食材管理',
      year: '2023',
      status: '大学卒業制作',
      role: 'プロダクトサービスシステム、ハードウェア連携、行動設計',
      methods: 'ユーザージャーニー、ハードウェアシナリオ、ライトガイド',
      next: 'スキャナーの行動と料理計画フローをさらに明確化する。',
      description: '食材の位置と期限を、スキャン、置き場所の案内、ライト表示で見えるようにする冷蔵庫システム。',
      question: '冷蔵庫は、食材がどこにあるかだけでなく、いつ使うべきかも知らせられるか。',
      process: [['入れる前', '磁吸式カメラモジュールで食材をスキャンし、種類、購入日、保存期限を登録する。'], ['入れる時', '保存場所を推薦し、ライトで置く位置を案内する。'], ['料理する時', 'スマホ、冷蔵庫画面、内部ライトで食材を見つけ、期限前の料理計画につなげる。']],
      outcomes: ['冷蔵庫を保存空間から時間管理インターフェースへ変える。', 'ハードウェア、モバイルUI、内部ライトをひとつの行動ループにする。', '食品ロス削減と整理された料理習慣を支える。'],
      image: image('6op'),
      detailImage: image('6jp'),
      href: '/works#fridge-timeline',
    },
  ],
  zh: [
    {
      id: 'co-creative-ai-training',
      title: '共创特化 AI 训练界面',
      type: 'AI 交互 / 共创',
      category: 'AI 交互 / 共创',
      year: '2025-2026',
      status: '概念系统推进中',
      role: '交互概念、UI 架构、训练数据流程',
      methods: '主导权映射、UI 原型、AI 工作流设计',
      next: '把用户操作如何变成训练信号，整理成更清楚的界面流程。',
      description: '通过显性 UI 让用户的意图、修正和判断进入 AI 训练过程，形成共创特化的系统逻辑。',
      question: '如何让 AI 的特化训练不是隐形吸收用户数据，而是保留人的主导权和共创感？',
      process: [['诱发主导权', '在 UI 上明确用户正在引导、修正或补充 AI 的时刻。'], ['贡献可视化', '把按钮、选择、修正和评论变成可见的数据痕迹。'], ['训练闭环', '让 AI 从结构化的人类输入中学习，同时保留用户作为作者的感觉。']],
      outcomes: ['把 AI 训练解释为共创过程，而不是被动数据采集。', '让用户的控制与贡献在界面上被看见。', '为特化型 AI 工作流建立基础结构。'],
      image: image('1op'),
      href: '/works#co-creative-ai-training',
    },
    {
      id: 'transparent-driving-hud',
      title: '智能驾驶防黑箱 AR-HUD',
      type: '出行 HMI / AR-HUD',
      category: '出行 HMI / AR-HUD',
      year: '2025-2026',
      status: '研究概念',
      role: 'HMI 研究、安全边界、感性评价计划',
      methods: '场景设计、AR-HUD 概念、人因工程梳理',
      next: '制作基线版、理性透明版和感性注意力版的视频刺激材料。',
      description: '通过 AR-HUD 可视化车间关系、不确定性和 AI 驾驶意图，降低自动驾驶的黑箱焦虑。',
      question: '自动驾驶如何在不增加驾驶员负担的前提下，展示它理解了什么、为什么这样决策？',
      process: [['透明层', '显示关键车辆、盲区感知和不确定性梯度，解释 AI 决策。'], ['教练层', '用幽灵路径和策略提示建立驾驶信心与主动驾驶意愿。'], ['安全退场', '接管请求出现时，500ms 内清除娱乐与非必要图层，只保留关键警示。']],
      outcomes: ['把信任、注意力和法规边界放在同一个 HMI 叙事里。', '定义基于视频的感性工学评价路径。', '把 AR-HUD 定位为人机共驾的透明界面。'],
      image: image('2op'),
      href: '/works#transparent-driving-hud',
    },
    {
      id: 'japanese-practice-echoes',
      title: '有回声的日语练习',
      type: '学习 UX / AI 陪伴',
      category: '学习 UX / AI 陪伴',
      year: '2025-2026',
      status: 'App 概念与演示板',
      role: '学习体验、反馈模型、UI 叙事',
      methods: '练习流程、成长痕迹地图、反馈界面',
      next: '把朗读练习和努力痕迹地图做成可交互的手机流程。',
      description: '一个把停顿、重读、犹豫和进步保存为成长证据的日语学习 App。',
      question: '如果 AI 不替人学习，而是帮助学习者看见自己付出的努力，会产生怎样的学习体验？',
      process: [['记录练习', '记录开口时间、停顿、重读和第一次顺利读过的表达。'], ['温和反馈', '不在朗读中打断，而是在练习后像陪读者一样整理。'], ['保存成长', '把反复尝试变成个人成长地图，让努力不再消失。']],
      outcomes: ['减少因为停顿和读错产生的羞耻感。', '让学习者感觉被陪伴，而不是被纠错。', '把个人学习历史保存成可见证据。'],
      image: image('3op'),
      detailImage: image('3cn'),
      href: '/works#japanese-practice-echoes',
    },
    {
      id: 'frametrace',
      title: 'FrameTrace',
      type: 'AR 眼镜 / 旅游摄影',
      category: 'AR 眼镜 / 旅游摄影',
      year: '2025-2026',
      status: '系统概念与服务场景',
      role: 'AR 交互、手势构图、空间记忆系统',
      methods: '手势场景、空间 UX、服务蓝图',
      next: '把 MVP 功能和未来空间共享功能分开整理。',
      description: '用双手取景框触发 AR 构图指导，推荐焦距、站位、角度和人物姿势的旅游摄影系统。',
      question: '能否把别人拍得好的经验，从二维图片攻略转化成真实地点中的 AR 参考？',
      process: [['手势构图', '用双手方框作为快速进入构图模式的自然入口。'], ['AR 引导', '在真实场景中提示焦距、移动距离、倾斜角度和构图边界。'], ['拍照痕迹', '保存位置、方向、镜头、姿势和构图记录，供后来者参考。']],
      outcomes: ['把旅游拍照从试错变成空间化指导。', '连接个人拍照记忆与共享 AR 参考。', '让未来感的空间社交概念具有可落地的 MVP 路径。'],
      image: image('4op'),
      detailImage: image('4cn'),
      href: '/works#frametrace',
    },
    {
      id: 'taste-again',
      title: '料理再会',
      type: '料理记忆 / 计划 App',
      category: '料理记忆 / 计划 App',
      year: '2025-2026',
      status: 'UX 概念与 App 板',
      role: '产品概念、料理记忆模型、移动端 UX',
      methods: '决策旅程、时间轴模型、提醒设计',
      next: '制作料理卡片、再食周期和本周计划的交互原型。',
      description: '一个帮助用户在合适时间重新想起过去喜欢料理的饮食记忆 App。',
      question: '如何让每天“吃什么”的选择，不再从零开始，而是从过去喜欢过的味道中重新出现？',
      process: [['记录', '把料理以味觉、场景、喜好、入手方式和备注记录成卡片。'], ['设定节奏', '为每道料理建立适合自己的再食周期。'], ['再次唤起', '在时间和状态合适时，把被忘记的料理轻轻推回用户面前。']],
      outcomes: ['减少每天选择吃什么的压力。', '建立个人料理记忆数据库。', '把推荐变成与过去美味的再会。'],
      image: image('5op'),
      detailImage: image('5cn'),
      href: '/works#taste-again',
    },
    {
      id: 'fridge-timeline',
      title: 'Fridge Timeline System',
      type: '产品系统 / 食材管理',
      category: '产品系统 / 食材管理',
      year: '2023',
      status: '大学毕业作品',
      role: '产品服务系统、硬件交互、行为设计',
      methods: '用户旅程、硬件场景、灯光引导交互',
      next: '进一步细化磁吸扫描器行为，并连接到料理计划流程。',
      description: '通过扫描、存放引导和灯光提示，让冰箱里的食材位置与期限都被看见的系统。',
      question: '冰箱能否不仅帮助用户找到食材，还帮助用户记住食材应该什么时候被使用？',
      process: [['放入前', '用磁吸摄像头扫描食材，记录类别、购买日期和预期保存期限。'], ['放入时', '根据类型和期限推荐存放区域，并用灯光提示具体位置。'], ['料理时', '通过手机、冰箱屏幕和内部灯光找到食材，并围绕临期食材规划料理。']],
      outcomes: ['把冰箱从储物空间转化为食材时间管理界面。', '把硬件、手机 UI 和内部灯光连接成完整行为闭环。', '帮助减少食物浪费，培养更有秩序的料理习惯。'],
      image: image('6op'),
      detailImage: image('6cn'),
      href: '/works#fridge-timeline',
    },
  ],
}
